const actions = {
  GET_HINDI_QUOTES: 'GET_HINDI_QUOTES',
  GET_GUJRATI_QUOTES: 'GET_GUJRATI_QUOTES',
  LOADING: 'LOADING',
  USER_LOGIN: 'USER_LOGIN',
  END_QUOTES:'END_QUOTES',
  
};
export default actions;
