/* Palette generated by Material Palette _ materialpaletteconst com/blue_grey/pink */

const primary_color = '#e0722d';

const defaultColors = {
  primary_color,
};

export default {
  ...defaultColors,
};
